name: Homebox
slug: homebox
description: 'Inventory and organization system built for the Home User'
version: latest
url: https://github.com/sysadminsmedia/homebox
logo: https://raw.githubusercontent.com/Oddiesea/homebox-ingress-ha-addon/main/homebox/logo.png
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 7745
panel_icon: mdi:package-variant
panel_title: Homebox
init: false
startup: services
boot: auto
map:
  - config:rw
ports:
  "7745/tcp": null
ports_description:
  "7745/tcp": "Web interface (Ingress)"
options: {}
schema: {}
image: ghcr.io/oddiesea/home-assistant-homebox-{arch}

